name: Build/release

on: workflow_dispatch
  
jobs:
  release:
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Prepare for app notarization
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.apple_api_key }}' > ~/private_keys/AuthKey_${{ secrets.apple_key_id }}.p8
      - name: Debug
        run: |
          ls -la ~/private_keys
          cat ~/private_keys/AuthKey_L87HMPTVG7.p8
